### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by fishpepper** [mitchese/shm-et340#4]
Hi! I am currently rewriting your code to support my (newer?) SMA energy meter. 
Your code does not work with mine, the binary offsets have shifted.

I am using a proper decoder similar to the one used in
https://github.com/snaptec/openWB/blob/master/packages/modules/sma_shm/speedwiredecoder.py

I was wondering what license this project uses? Are you ok with releasing it under the GPL?

**Comment by TimBoWi** [comment]
If you have an updated Version let me try @fishpepper 
i got the problem that AC-Input doesnt show reliable results and no AC-Loads.

**Comment by slankes** [comment]
I am running your version now as well because the "original" didn't work for me.

@mitchese can you clarify the license? Would you be interested in merging @fishpepper changes into the main?
